import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./_components/navbar";
import { Toaster } from "react-hot-toast";
import { UserProvider } from "./_components/userContext";
import { CategoryProvider } from "./_components/categoryContext";

export const metadata: Metadata = {
  title: "Bra Thobi's POS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const currentPath = usePathname()
  return (
    <html lang="en">
      <body className="bg-gradient-to-r from-white to-gray-400 h-full ">
        <UserProvider>
          <CategoryProvider>
          {/* <NavBar/> */}
          {children}
          <Toaster />
          </CategoryProvider>
        </UserProvider>
      </body>
    </html>
  );
}
